### PR TITLE
Minor Fixes for ILS

### PR DESCRIPTION
**Pull request by kingthorin**
* Correct a typo.
* Remove unused variables.
* Standardized on tabs for the indent (added vim mode line at the end of the file).

(Eclipse also points out two unused imports, I've left them in place as they're used in currently commented out code.)

### CODE REVIEW

**Comment by kingthorin** [comment]
The class also seems to use a mix of tabs/spaces for indentation. I didn't fix that in this PR as I was hesitant to mix whitespace changes with other stuff. If you're happy to have it cleaned up (as part of this PR) let me know and I'll revise the PR.

**Comment by veggiespam** [comment]
Please, clean it to either spaces or tabs, which ever preference of yours is fine.  Update or add an emacs and vim line at the bottom.

**Comment by kingthorin** [comment]
>  Update or add an emacs and vim line at the bottom.

You mean something like this?
`// set autoindent noexpandtab tabstop=4 shiftwidth=4`

Note I'm not particularly set on one method or another, but feel consistency is important. (In this case there seems to be more tabbed indents than spaced indents so I'd probably replace every 4 space string with a single tab.)

**Comment by veggiespam** [comment]
I agree, consistency; I am bad at keeping it when I get patches, I will do better.  And, yes, that mode line works.  Does the world still need an emacs mode line too?

**Pull request merged**
